language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false
  
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction

- sh -c mysql -e 'CREATE DATABASE cakephp_test;'

- phpenv rehash
- set +H

script:
  - sh -c phpunit
